### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by jfgreco** [jasonfsmitty/krach#1]
First off thank you for creating this. Just found it. Very useful. 

Ran the scripts in order as described in the readme. The get-scores script pulls down all the proper files per division, but also appears to create the sub-divisional files as well, which are empty thus raising the typeerror exception. I suppose this is due to them updating the web site and setting up for playoffs. 

If you remove the sub-division files the ahf script runs as expected. 

Looks like there needs to be some check logic in the krach.py file to check if there are actually any games to read. 

AhfScoreReader -> read line 404 is raising the error because game doesn't have any games.

**Comment by jasonfsmitty** [comment]
Thanks for the feedback, glad you found it useful.

Yeah, they seem to be pre-creating the playoff brackets as stand-alone divisions.  I had a local fix for this, but forgot to pushed it up.

With the fix, you should be good to go.  Feel free to reach out with any other feedback.
