### ISSUE TITLE
Support split AHF divisions - Gretzky/Lemieux

### ISSUE THREAD

**Issue by jasonfsmitty** [jasonfsmitty/krach#6]
Some divisions such as 14U-A are split into two separate divisions, called Gretzky and Lemieux.  The tool had been ignoring these and lumping everyone together in one super-division.

Update the tool to treat these as separate divsions.

**Comment by berky2755** [comment]
I did a git clone today and did not see where the divisions are separated into the sub-divisions for gretzky and lemieux. Did I do something wrong or does it not account for that yet? Thanks!

**Comment by jasonfsmitty** [comment]
No worries.  Question for you ... do you know if the separate divisions only play games within their Gretzky/Lemieux division, or do they play teams in both?

**Comment by berky2755** [comment]
Yes, that is very much possible, although it generally doesn't happen a lot.  However, to throw a bigger wrench in the gears, it is also possible for some teams to play teams in another division entirely... example; A Silver team playing a B Gold team.  This also doesn't happen very often, but there are some games that get scheduled that way (likely rescheduled during the season or as part of a showcase) when teams aren't quite properly placed.
